-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 08:41:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Reg_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Reg_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Reg_escola` DEFAULT CHARACTER SET utf8 ;
USE `Reg_escola` ;

-- -----------------------------------------------------
-- Table `Reg_escola`.`Alunes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reg_escola`.`Alunes` ;

CREATE TABLE IF NOT EXISTS `Reg_escola`.`Alunes` (
  `Id` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Idade` INT(3) NOT NULL,
  `Turma` VARCHAR(3) NOT NULL,
  `Serie` INT(2) NOT NULL,
  `Nota` INT(2) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


 select * from Alunes where nota > 7
