-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 19:35:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Banco_eCommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Banco_eCommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Banco_eCommerce` DEFAULT CHARACTER SET utf8 ;
USE `Banco_eCommerce` ;

-- -----------------------------------------------------
-- Table `Banco_eCommerce`.`Tab_Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco_eCommerce`.`Tab_Produtos` (
  `Produtos` VARCHAR(20) NOT NULL,
  `Quantidade` INT(3) NOT NULL,
  `Preço` DECIMAL(3) NOT NULL,
  PRIMARY KEY (`Produtos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
