-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 17:07:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_farmacia_do_bem` DEFAULT CHARACTER SET utf8 ;
USE `db_farmacia_do_bem` ;

-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`tb_categoria` (
  `id_Produto` INT NOT NULL,
  `semPrescricao_Categoria` VARCHAR(45) NOT NULL,
  `comPrescricao_Categoria` VARCHAR(45) NOT NULL,
  `livre_Categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`tb_produto` (
  `nome_Produto` VARCHAR(45) NOT NULL,
  `valor_Produto` VARCHAR(45) NOT NULL,
  `tipo_Produto` VARCHAR(45) NOT NULL,
  `tb_categoria_id_Produto` INT NOT NULL,
  PRIMARY KEY (`tb_categoria_id_Produto`),
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`tb_categoria_id_Produto`)
    REFERENCES `db_farmacia_do_bem`.`tb_categoria` (`id_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SELECT * FROM db_farmacia_do_bem.tb_categoria;

INSERT INTO tb_categoria (id_Produto, semPrescricao_Categoria, comPrescricao_Categoria, livre_Categoria)
VALUES (2,"Com prescrição medica","Sem prescrição medica", "Na loja");

SELECT * FROM db_farmacia_do_bem.tb_produto;

INSERT INTO tb_produto (nome_Produto, valor_Produto, tipo_Produto, tb_categoria_id_Produto)
VALUES ("Naridrim", 24.00, "Uso nasal", 2);

-- ALTER TABLE tb_produto change valor_Produto valor_Produto decimal (5,2) NOT NULL;

-- SELECT * FROM tb_produto WHERE valor_Produto > 50,
-- SELECT * FROM tb_produto WHERE valor_Produto  between 3 AND 60;
-- SELECT * FROM tb_produto WHERE nome_Produto  like "%B%";
-- SELECT * FROM tb_categoria inner join  tb_produto; 
-- SELECT * FROM tb_categoria WHERE comPrescricao_Categoria like "Com prescrição medica";