-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 15:47:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `id_Pizza` INT NOT NULL AUTO_INCREMENT,
  `nome_Pizza` VARCHAR(45) NOT NULL,
  `valor_Puzza` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_Pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categoria` (
  `id_Categoria` INT NOT NULL AUTO_INCREMENT,
  `sabor_Categoria` VARCHAR(45) NOT NULL,
  `borda_Categoria` VARCHAR(45) NOT NULL,
  `tabamho_Categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza_has_tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (
  `tb_pizza_id_Pizza` INT NOT NULL,
  `tb_categoria_id_Categoria` INT NOT NULL,
  PRIMARY KEY (`tb_pizza_id_Pizza`, `tb_categoria_id_Categoria`),
  INDEX `fk_tb_pizza_has_tb_categoria_tb_categoria1_idx` (`tb_categoria_id_Categoria` ASC) VISIBLE,
  INDEX `fk_tb_pizza_has_tb_categoria_tb_pizza_idx` (`tb_pizza_id_Pizza` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizza_has_tb_categoria_tb_pizza`
    FOREIGN KEY (`tb_pizza_id_Pizza`)
    REFERENCES `db_pizzaria_legal`.`tb_pizza` (`id_Pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pizza_has_tb_categoria_tb_categoria1`
    FOREIGN KEY (`tb_categoria_id_Categoria`)
    REFERENCES `db_pizzaria_legal`.`tb_categoria` (`id_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM db_pizzaria_legal.tb_categoria;

INSERT INTO tb_categoria (sabor_Categoria, borda_Categoria, tabamho_Categoria) 
VALUES 
("Calabresa", "Simples", "Broto"),
("Marguerita","recheada","grande");

SELECT * FROM db_pizzaria_legal.tb_pizza;

INSERT INTO tb_pizza (nome_Pizza, valor_Puzza) 
VALUES("Naruto", 50), ("jiraya", 45), ("Sasuke", 46);

-- SELECT * FROM tb_pizza WHERE valor_Puzza > 45,
-- SELECT * FROM tb_pizza WHERE valor_Puzza  between 29 AND 60;
-- SELECT * FROM tb_pizza WHERE nome_Pizza  like "%C%";
-- SELECT * FROM tb_pizza inner join  tb_categoria; 
-- SELECT * FROM tb_categoria WHERE sabor_Categoria like "Sorvete";
-- SELECT * FROM tb_categoria WHERE sabor_Categoria like "Calabresa";
