-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 18:40:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rh_Empresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rh_Empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rh_Empresa` DEFAULT CHARACTER SET utf8 ;
USE `rh_Empresa` ;

-- -----------------------------------------------------
-- Table `rh_Empresa`.`Tab_Funcionaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_Empresa`.`Tab_Funcionaries` (
  `nome` VARCHAR(30) NOT NULL,
  `idade` INT(3) NOT NULL,
  `Id_Funcionarie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh_Empresa`.`Tab_Funcionarie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_Empresa`.`Tab_Funcionarie` (
  `idTab_Funcionarie` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Idade` INT(3) NOT NULL,
  `Salario` DECIMAL(6) NOT NULL,
  PRIMARY KEY (`idTab_Funcionarie`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

 select * from Tab_Funcionarie where Salario  > 500
# select * from Tab_Funcionarie where Salario < 500